default_stages: [commit, push]

default_language_version:
  python: python3.7

exclude: 'venv'

fail_fast: false

repos:
  - repo: local
    hooks:
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        language: python
        entry: poetry check
        pass_filenames: false
        files: pyproject.toml
        always_run: true
        additional_dependencies: [poetry]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [
          --skip=B101
        ]

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/myint/docformatter
    rev: v1.2
    hooks:
      - id: docformatter
        args: [
          --in-place,
          --wrap-summaries=120,
          --wrap-descriptions=120,
          --make-summary-multi-line,
          --pre-summary-newline
        ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config
        args: [
          --application-directories, 'src:.'
        ]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.3
    hooks:
      - id: pylint
        additional_dependencies: [toml]
        args: [
          --max-line-length=120,
          --jobs=8,
          --disable=E0401,
          --disable=R0902,
        ]
