os: linux
dist: bionic

language: python
python:
  - 3.6

stages:
  - deploy

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_0b2a1fcc9951_key -iv $encrypted_0b2a1fcc9951_iv -in .travis/travis-ci_service_account.json.enc -out travis-ci_service_account.json -d

jobs:
  include:
    - stage: deploy
      script:
        - cat travis-ci_service_account.json | docker login -u _json_key https://gcr.io --password-stdin
        - make docker_publish
