[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "distributed_nlp_emails"
version = "0.0.1"
description = """
Applying Natural Language Processing (NLP) techniques to detect topics, summarize, and identify actionable emails in a
distributed fashion using Spark and TensorFlow
"""
authors = ["Cathal Mullan <cmullan@proofpoint.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.7.*"
tqdm = "^4.36"
requests = "^2.22"
validators = "^0.14.0"
talon = "^1.4"
bs4 = "^0.0.1"
pycld3 = "^0.14.0"
faker = "^2.0"
spacy = "^2.2"
toml = "^0.10.0"
pyarrow = "^0.15.0"
pandas = "^0.25.2"

[tool.poetry.dev-dependencies]
pre-commit = "1.18.2"
pytest = "5.1.0"
pytest-cov = "2.7.1"

[tool.poetry.scripts]
get_enron_dataset = "nlp_emails.download.get_enron_dataset:get_enron_dataset"
get_spacy_model = "nlp_emails.download.get_spacy_model:get_spacy_model"

[tool.black]
line-length = 120
target_version = ['py37']

[tool.isort]
line_length = 120
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = true
known_third_party = ["bs4", "faker", "pandas", "pyarrow", "pytest", "requests", "spacy", "talon", "toml", "tqdm", "validators"]
